### ISSUE TITLE
getting Fatal error: Uncaught Error: Class "Nonce\Config\Config"

### ISSUE THREAD

**Issue by ashish200025** [elhardoum/nonce-php#1]
can you please check why

Fatal error: Uncaught Error: Class "Nonce\Config\Config ??

**Comment by elhardoum** [comment]
Hi Ashish,

Could you provide the full error message please? You may not be loading the composer autoload file correctly, if it says class not found.

```php
require '/path/to/vendor/autoload.php';
```

**Comment by ashish200025** [comment]
Thank you sir
its working perfectly :)

**Comment by elhardoum** [comment]
My pleasure. Thank you as well!
Closing the issue
